title: Whisper Studios
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.25
  rhythmicContrast: 1
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#5b5b4d'
    - '#2b2b25'
    - '#b3b3aa'
  lightness: 0.5
navigation:
  - id: 4c8beaef-9898-4276-90fb-cd888a8db2b9
    name: About us
    type: content
  - id: 098e04bc-b39a-4878-b2f5-1489edbe42bd
    name: Sounds
    type: content
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Whisper Studios
opengraph:
  image: null
  type: null
  appId: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/752c254f-7171-429a-bce0-ab1dc597786b.pdf
typography_spectrum: 0.5268817
layout_spectrum: 0.4193548
