name: Whisper Studios
favicon: null
layout_spectrum: 0.51779
typography_spectrum: 0.4808
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Whisper Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22150d'
    - '#b6a289'
    - '#daf700'
    - '#789100'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
