name: Whisper Studios
favicon: null
layout_spectrum: 0
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Whisper Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030201'
    - '#423830'
    - '#FCFDFA'
    - '#928776'
    - '#B4B3AD'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0
purpose: []
